# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(default='')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='edge',
            name='end_node',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='end_node', to='network_editor.Node'),
        ),
        migrations.AddField(
            model_name='edge',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_editor.Network'),
        ),
        migrations.AddField(
            model_name='edge',
            name='start_node',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='start_node', to='network_editor.Node'),
        ),
    ]
